[2024-06-27T06:24:08.732+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-27T06:24:09.274+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-27T06:24:09.326+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T06:24:09.497+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test.get_urls_task manual__2024-06-27T06:24:00.522412+00:00 [queued]>
[2024-06-27T06:24:09.535+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test.get_urls_task manual__2024-06-27T06:24:00.522412+00:00 [queued]>
[2024-06-27T06:24:09.539+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-27T06:24:09.748+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_urls_task> on 2024-06-27 06:24:00.522412+00:00
[2024-06-27T06:24:09.762+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T06:24:09.768+0000] {standard_task_runner.py:63} INFO - Started process 97 to run task
[2024-06-27T06:24:09.771+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test', 'get_urls_task', 'manual__2024-06-27T06:24:00.522412+00:00', '--job-id', '614', '--raw', '--subdir', 'DAGS_FOLDER/first_out.py', '--cfg-path', '/tmp/tmpnnjqenop']
[2024-06-27T06:24:09.780+0000] {standard_task_runner.py:91} INFO - Job 614: Subtask get_urls_task
[2024-06-27T06:24:10.001+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-27T06:24:10.033+0000] {task_command.py:426} INFO - Running <TaskInstance: test.get_urls_task manual__2024-06-27T06:24:00.522412+00:00 [running]> on host ccfa35e0da07
[2024-06-27T06:24:10.038+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 97)
[2024-06-27T06:24:10.043+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 97)
[2024-06-27T06:24:10.044+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-06-27T06:24:10.339+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-27T06:24:10.498+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test' AIRFLOW_CTX_TASK_ID='get_urls_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T06:24:00.522412+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T06:24:00.522412+00:00'
[2024-06-27T06:24:10.501+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T06:24:29.654+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T06:24:29.656+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_out.py", line 29, in run_selenium_job
    page_id = functions_instance.get_id(link)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fun/fun_user.py", line 83, in get_id
    start, end = matches.span()
                 ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'span'
[2024-06-27T06:24:29.784+0000] {taskinstance.py:562} DEBUG - Task Duration set to 20.285797
[2024-06-27T06:24:29.796+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2024-06-27T06:24:29.798+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=test, task_id=get_urls_task, run_id=manual__2024-06-27T06:24:00.522412+00:00, execution_date=20240627T062400, start_date=20240627T062409, end_date=20240627T062429
[2024-06-27T06:24:29.982+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 614 for task get_urls_task ('NoneType' object has no attribute 'span'; 97)
[2024-06-27T06:24:30.048+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T06:24:30.153+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T06:24:30.165+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
