[2024-06-26T07:55:21.010+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:55:21.053+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:55:21.066+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T07:55:21.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: U.get_urls_task manual__2024-06-26T07:55:19.605651+00:00 [queued]>
[2024-06-26T07:55:21.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: U.get_urls_task manual__2024-06-26T07:55:19.605651+00:00 [queued]>
[2024-06-26T07:55:21.118+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-26T07:55:21.138+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_urls_task> on 2024-06-26 07:55:19.605651+00:00
[2024-06-26T07:55:21.145+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2643) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T07:55:21.147+0000] {standard_task_runner.py:63} INFO - Started process 2644 to run task
[2024-06-26T07:55:21.146+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'U', 'get_urls_task', 'manual__2024-06-26T07:55:19.605651+00:00', '--job-id', '537', '--raw', '--subdir', 'DAGS_FOLDER/first_out.py', '--cfg-path', '/tmp/tmpgbxtmshu']
[2024-06-26T07:55:21.149+0000] {standard_task_runner.py:91} INFO - Job 537: Subtask get_urls_task
[2024-06-26T07:55:21.198+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:55:21.205+0000] {task_command.py:426} INFO - Running <TaskInstance: U.get_urls_task manual__2024-06-26T07:55:19.605651+00:00 [running]> on host ccfa35e0da07
[2024-06-26T07:55:21.206+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 2644)
[2024-06-26T07:55:21.207+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 2644)
[2024-06-26T07:55:21.208+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-06-26T07:55:21.261+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:55:21.314+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='U' AIRFLOW_CTX_TASK_ID='get_urls_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T07:55:19.605651+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T07:55:19.605651+00:00'
[2024-06-26T07:55:21.316+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T07:55:24.344+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T07:55:24.346+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_out.py", line 26, in run_selenium_job
    functions_instance = User_Functions()
                         ^^^^^^^^^^^^^^^^
TypeError: User_Functions.__init__() missing 1 required positional argument: 'includesPosts'
[2024-06-26T07:55:24.379+0000] {taskinstance.py:562} DEBUG - Task Duration set to 3.271761
[2024-06-26T07:55:24.382+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2024-06-26T07:55:24.383+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=U, task_id=get_urls_task, run_id=manual__2024-06-26T07:55:19.605651+00:00, execution_date=20240626T075519, start_date=20240626T075521, end_date=20240626T075524
[2024-06-26T07:55:24.405+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 537 for task get_urls_task (User_Functions.__init__() missing 1 required positional argument: 'includesPosts'; 2644)
[2024-06-26T07:55:24.458+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T07:55:24.486+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T07:55:24.489+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
