[2024-06-27T09:02:48.354+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: USER1.process_link_0 manual__2024-06-27T09:00:06.822650+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
