[2024-06-26T07:30:23.452+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:30:23.500+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:30:23.517+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T07:30:23.557+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PAGE1.process_link_0 manual__2024-06-26T07:20:29.160351+00:00 [queued]>
[2024-06-26T07:30:23.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PAGE1.process_link_0 manual__2024-06-26T07:20:29.160351+00:00 [queued]>
[2024-06-26T07:30:23.572+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-06-26T07:30:23.596+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_link_0> on 2024-06-26 07:20:29.160351+00:00
[2024-06-26T07:30:23.604+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1849) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T07:30:23.606+0000] {standard_task_runner.py:63} INFO - Started process 1851 to run task
[2024-06-26T07:30:23.607+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'PAGE1', 'process_link_0', 'manual__2024-06-26T07:20:29.160351+00:00', '--job-id', '530', '--raw', '--subdir', 'DAGS_FOLDER/page_***.py', '--cfg-path', '/tmp/tmpvrmys3cz']
[2024-06-26T07:30:23.609+0000] {standard_task_runner.py:91} INFO - Job 530: Subtask process_link_0
[2024-06-26T07:30:23.709+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:30:23.717+0000] {task_command.py:426} INFO - Running <TaskInstance: PAGE1.process_link_0 manual__2024-06-26T07:20:29.160351+00:00 [running]> on host ccfa35e0da07
[2024-06-26T07:30:23.718+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 1851)
[2024-06-26T07:30:23.719+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 1851)
[2024-06-26T07:30:23.719+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-06-26T07:30:23.773+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:30:23.851+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PAGE1' AIRFLOW_CTX_TASK_ID='process_link_0' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T07:20:29.160351+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T07:20:29.160351+00:00'
[2024-06-26T07:30:23.853+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T07:30:25.923+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (1): localhost:35599
[2024-06-26T07:30:26.814+0000] {connectionpool.py:549} DEBUG - http://localhost:35599 "POST /session HTTP/1.1" 200 0
[2024-06-26T07:30:27.558+0000] {connectionpool.py:549} DEBUG - http://localhost:35599 "POST /session/b5fdea27630d443e86852f6eeee9b82f/url HTTP/1.1" 200 0
[2024-06-26T07:30:27.592+0000] {connectionpool.py:549} DEBUG - http://localhost:35599 "POST /session/b5fdea27630d443e86852f6eeee9b82f/element HTTP/1.1" 200 0
[2024-06-26T07:30:27.622+0000] {connectionpool.py:549} DEBUG - http://localhost:35599 "GET /session/b5fdea27630d443e86852f6eeee9b82f/element/f.45E368965295CACA2BC402229CABAF37.d.3BF65FAFF7313530C1ECB60D50EE3786.e.2/text HTTP/1.1" 200 0
[2024-06-26T07:30:27.624+0000] {logging_mixin.py:188} INFO - 35182380619
[2024-06-26T07:30:27.893+0000] {connectionpool.py:549} DEBUG - http://localhost:35599 "POST /session/b5fdea27630d443e86852f6eeee9b82f/url HTTP/1.1" 200 0
[2024-06-26T07:30:27.917+0000] {connectionpool.py:549} DEBUG - http://localhost:35599 "POST /session/b5fdea27630d443e86852f6eeee9b82f/element HTTP/1.1" 200 0
[2024-06-26T07:30:27.943+0000] {connectionpool.py:549} DEBUG - http://localhost:35599 "GET /session/b5fdea27630d443e86852f6eeee9b82f/element/f.45E368965295CACA2BC402229CABAF37.d.D0DFAF7FC7B89CA307FE60A81A89B1DF.e.4/text HTTP/1.1" 200 0
[2024-06-26T07:30:27.945+0000] {logging_mixin.py:188} INFO - ok
[2024-06-26T07:30:31.513+0000] {connectionpool.py:549} DEBUG - http://localhost:35599 "POST /session/b5fdea27630d443e86852f6eeee9b82f/url HTTP/1.1" 200 0
[2024-06-26T07:30:31.529+0000] {connectionpool.py:549} DEBUG - http://localhost:35599 "POST /session/b5fdea27630d443e86852f6eeee9b82f/element HTTP/1.1" 200 0
[2024-06-26T07:30:31.747+0000] {connectionpool.py:549} DEBUG - http://localhost:35599 "GET /session/b5fdea27630d443e86852f6eeee9b82f/element/f.45E368965295CACA2BC402229CABAF37.d.6C8DAA18ABF20DCAD25CA51E1F16FC3A.e.6/text HTTP/1.1" 200 0
[2024-06-26T07:30:33.722+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-26T07:30:33.723+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T07:30:33.728+0000] {process_utils.py:132} INFO - Sending 15 to group 1851. PIDs of all processes in the group: [1883, 1889, 1904, 1905, 1929, 1907, 1965, 1955, 1956, 1851]
[2024-06-26T07:30:33.729+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1851
[2024-06-26T07:30:33.730+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-26T07:30:33.733+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (2): localhost:35599
[2024-06-26T07:30:33.740+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab09caf7a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b5fdea27630d443e86852f6eeee9b82f
[2024-06-26T07:30:33.741+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (3): localhost:35599
[2024-06-26T07:30:33.743+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab09d45160>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b5fdea27630d443e86852f6eeee9b82f
[2024-06-26T07:30:33.744+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (4): localhost:35599
[2024-06-26T07:30:33.746+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab09b7d8e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b5fdea27630d443e86852f6eeee9b82f
[2024-06-26T07:30:33.746+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1955, status='terminated', started='07:30:25') (1955) terminated with exit code None
[2024-06-26T07:30:33.749+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (5): localhost:35599
[2024-06-26T07:30:33.750+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1907, status='terminated', started='07:30:25') (1907) terminated with exit code None
[2024-06-26T07:30:33.884+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1956, status='terminated', started='07:30:25') (1956) terminated with exit code None
[2024-06-26T07:30:33.941+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T07:30:33.958+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2024-06-26T07:30:34.019+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1851, status='terminated', exitcode=0, started='07:30:22') (1851) terminated with exit code 0
[2024-06-26T07:30:34.022+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1883, status='terminated', started='07:30:24') (1883) terminated with exit code None
[2024-06-26T07:30:34.024+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1905, status='terminated', started='07:30:25') (1905) terminated with exit code None
[2024-06-26T07:30:34.159+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1965, status='terminated', started='07:30:26') (1965) terminated with exit code None
[2024-06-26T07:30:34.160+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1904, status='terminated', started='07:30:25') (1904) terminated with exit code None
[2024-06-26T07:30:34.161+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1929, status='terminated', started='07:30:25') (1929) terminated with exit code None
[2024-06-26T07:30:34.166+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1889, status='terminated', started='07:30:25') (1889) terminated with exit code None
