[2024-06-26T07:30:09.325+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:30:09.388+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:30:09.449+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T07:30:09.561+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PAGE1.process_link_0 manual__2024-06-26T07:20:29.160351+00:00 [queued]>
[2024-06-26T07:30:09.590+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PAGE1.process_link_0 manual__2024-06-26T07:20:29.160351+00:00 [queued]>
[2024-06-26T07:30:09.591+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-26T07:30:09.622+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_link_0> on 2024-06-26 07:20:29.160351+00:00
[2024-06-26T07:30:09.631+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1699) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T07:30:09.633+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'PAGE1', 'process_link_0', 'manual__2024-06-26T07:20:29.160351+00:00', '--job-id', '528', '--raw', '--subdir', 'DAGS_FOLDER/page_***.py', '--cfg-path', '/tmp/tmptki4debi']
[2024-06-26T07:30:09.634+0000] {standard_task_runner.py:63} INFO - Started process 1700 to run task
[2024-06-26T07:30:09.634+0000] {standard_task_runner.py:91} INFO - Job 528: Subtask process_link_0
[2024-06-26T07:30:09.686+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:30:09.693+0000] {task_command.py:426} INFO - Running <TaskInstance: PAGE1.process_link_0 manual__2024-06-26T07:20:29.160351+00:00 [running]> on host ccfa35e0da07
[2024-06-26T07:30:09.693+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 1700)
[2024-06-26T07:30:09.694+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 1700)
[2024-06-26T07:30:09.695+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-06-26T07:30:09.751+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:30:09.825+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PAGE1' AIRFLOW_CTX_TASK_ID='process_link_0' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T07:20:29.160351+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T07:20:29.160351+00:00'
[2024-06-26T07:30:09.828+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T07:30:11.955+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (1): localhost:53945
[2024-06-26T07:30:12.830+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "POST /session HTTP/1.1" 200 0
[2024-06-26T07:30:13.410+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "POST /session/4771dc6c980ce4b19969e5bc35b107d2/url HTTP/1.1" 200 0
[2024-06-26T07:30:13.448+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "POST /session/4771dc6c980ce4b19969e5bc35b107d2/element HTTP/1.1" 200 0
[2024-06-26T07:30:13.480+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "GET /session/4771dc6c980ce4b19969e5bc35b107d2/element/f.C73C4A1178EE0E8130B5DC19A5632952.d.C2D6F568E946AE687DBDAB0C5C7E30BB.e.2/text HTTP/1.1" 200 0
[2024-06-26T07:30:13.482+0000] {logging_mixin.py:188} INFO - 35182380619
[2024-06-26T07:30:13.811+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "POST /session/4771dc6c980ce4b19969e5bc35b107d2/url HTTP/1.1" 200 0
[2024-06-26T07:30:13.828+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "POST /session/4771dc6c980ce4b19969e5bc35b107d2/element HTTP/1.1" 200 0
[2024-06-26T07:30:13.849+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "GET /session/4771dc6c980ce4b19969e5bc35b107d2/element/f.C73C4A1178EE0E8130B5DC19A5632952.d.2F97DA98C618F78B1EC2E0AD61695B9A.e.4/text HTTP/1.1" 200 0
[2024-06-26T07:30:13.851+0000] {logging_mixin.py:188} INFO - ok
[2024-06-26T07:30:16.981+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "POST /session/4771dc6c980ce4b19969e5bc35b107d2/url HTTP/1.1" 200 0
[2024-06-26T07:30:16.997+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "POST /session/4771dc6c980ce4b19969e5bc35b107d2/element HTTP/1.1" 200 0
[2024-06-26T07:30:17.174+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "GET /session/4771dc6c980ce4b19969e5bc35b107d2/element/f.C73C4A1178EE0E8130B5DC19A5632952.d.70EB97C03DEC7A57E3205E03CD95F9D0.e.6/text HTTP/1.1" 200 0
[2024-06-26T07:30:23.473+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "POST /session/4771dc6c980ce4b19969e5bc35b107d2/url HTTP/1.1" 200 0
[2024-06-26T07:30:23.502+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "POST /session/4771dc6c980ce4b19969e5bc35b107d2/element HTTP/1.1" 200 0
[2024-06-26T07:30:23.755+0000] {connectionpool.py:549} DEBUG - http://localhost:53945 "GET /session/4771dc6c980ce4b19969e5bc35b107d2/element/f.C73C4A1178EE0E8130B5DC19A5632952.d.8537DB1B3FC6D969123507E05B6A533E.e.8/text HTTP/1.1" 200 0
[2024-06-26T07:30:23.769+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:30:24.949+0000] {local_task_job_runner.py:288} WARNING - Recorded pid 1851 does not match the current pid 1700
[2024-06-26T07:30:24.952+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T07:30:24.966+0000] {process_utils.py:132} INFO - Sending 15 to group 1700. PIDs of all processes in the group: [1750, 1756, 1771, 1772, 1796, 1774, 1836, 1826, 1827, 1700]
[2024-06-26T07:30:24.968+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1700
[2024-06-26T07:30:24.969+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-26T07:30:24.974+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (2): localhost:53945
[2024-06-26T07:30:24.986+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab09b4a6f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4771dc6c980ce4b19969e5bc35b107d2
[2024-06-26T07:30:24.987+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (3): localhost:53945
[2024-06-26T07:30:24.989+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab09bcab10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4771dc6c980ce4b19969e5bc35b107d2
[2024-06-26T07:30:24.990+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (4): localhost:53945
[2024-06-26T07:30:24.996+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab09b4adb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4771dc6c980ce4b19969e5bc35b107d2
[2024-06-26T07:30:25.000+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (5): localhost:53945
[2024-06-26T07:30:25.178+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T07:30:25.190+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/page_airflow.py", line 126, in process_link
    result = run_selenium_job(link)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/page_airflow.py", line 68, in run_selenium_job
    result = functions_instance.get_all_data(driver, page_id, access_token)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fun/fun_page.py", line 246, in get_all_data
    posts_dict = self.get_posts(driver, user_id, access_token)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fun/fun_page.py", line 94, in get_posts
    driver.get(next_url)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 302, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 322, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/poolmanager.py", line 444, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 708, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-26T07:30:25.247+0000] {taskinstance.py:562} DEBUG - Task Duration set to 1.689253
[2024-06-26T07:30:25.250+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2024-06-26T07:30:25.250+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=PAGE1, task_id=process_link_0, run_id=manual__2024-06-26T07:20:29.160351+00:00, execution_date=20240626T072029, start_date=20240626T073023, end_date=20240626T073025
[2024-06-26T07:30:25.244+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1774, status='terminated', started='07:30:11') (1774) terminated with exit code None
[2024-06-26T07:30:25.252+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1796, status='terminated', started='07:30:11') (1796) terminated with exit code None
[2024-06-26T07:30:25.253+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1750, status='terminated', started='07:30:11') (1750) terminated with exit code None
[2024-06-26T07:30:25.254+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1836, status='terminated', started='07:30:12') (1836) terminated with exit code None
[2024-06-26T07:30:25.255+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1826, status='terminated', started='07:30:11') (1826) terminated with exit code None
[2024-06-26T07:30:25.256+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1772, status='terminated', started='07:30:11') (1772) terminated with exit code None
[2024-06-26T07:30:25.390+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1827, status='terminated', started='07:30:11') (1827) terminated with exit code None
[2024-06-26T07:30:25.407+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1756, status='terminated', started='07:30:11') (1756) terminated with exit code None
[2024-06-26T07:30:25.408+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1771, status='terminated', started='07:30:11') (1771) terminated with exit code None
[2024-06-26T07:30:25.410+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1700, status='terminated', exitcode=2, started='07:30:08') (1700) terminated with exit code 2
