[2024-06-26T06:56:54.373+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T06:56:54.450+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T06:56:54.495+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T06:56:54.601+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: selenium_minio.run_selenium_task manual__2024-06-26T06:56:49.633393+00:00 [queued]>
[2024-06-26T06:56:54.625+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: selenium_minio.run_selenium_task manual__2024-06-26T06:56:49.633393+00:00 [queued]>
[2024-06-26T06:56:54.626+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-26T06:56:54.655+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_selenium_task> on 2024-06-26 06:56:49.633393+00:00
[2024-06-26T06:56:54.663+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=903) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T06:56:54.666+0000] {standard_task_runner.py:63} INFO - Started process 944 to run task
[2024-06-26T06:56:54.666+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'selenium_minio', 'run_selenium_task', 'manual__2024-06-26T06:56:49.633393+00:00', '--job-id', '519', '--raw', '--subdir', 'DAGS_FOLDER/crawl_minio.py', '--cfg-path', '/tmp/tmp7zkxlfbt']
[2024-06-26T06:56:54.667+0000] {standard_task_runner.py:91} INFO - Job 519: Subtask run_selenium_task
[2024-06-26T06:56:54.731+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T06:56:54.740+0000] {task_command.py:426} INFO - Running <TaskInstance: selenium_minio.run_selenium_task manual__2024-06-26T06:56:49.633393+00:00 [running]> on host ccfa35e0da07
[2024-06-26T06:56:54.741+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 944)
[2024-06-26T06:56:54.742+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 944)
[2024-06-26T06:56:54.743+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-06-26T06:56:54.815+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T06:56:54.905+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='selenium_minio' AIRFLOW_CTX_TASK_ID='run_selenium_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T06:56:49.633393+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T06:56:49.633393+00:00'
[2024-06-26T06:56:54.907+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T06:56:56.667+0000] {logging_mixin.py:188} INFO - ok
[2024-06-26T06:57:20.095+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-06-26T06:57:20.096+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T06:57:20.112+0000] {process_utils.py:132} INFO - Sending 15 to group 944. PIDs of all processes in the group: [975, 981, 996, 997, 1022, 999, 1052, 1038, 1039, 944]
[2024-06-26T06:57:20.114+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 944
[2024-06-26T06:57:20.115+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-26T06:57:20.129+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab09b42030>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/74ce502df0e8a22e3d1c928dc6e3d7df
[2024-06-26T06:57:20.131+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab09b424b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/74ce502df0e8a22e3d1c928dc6e3d7df
[2024-06-26T06:57:20.132+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab09b42960>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/74ce502df0e8a22e3d1c928dc6e3d7df
[2024-06-26T06:57:20.128+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1038, status='terminated', started='06:56:54') (1038) terminated with exit code None
[2024-06-26T06:57:20.188+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1022, status='terminated', started='06:56:54') (1022) terminated with exit code None
[2024-06-26T06:57:20.325+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1039, status='terminated', started='06:56:54') (1039) terminated with exit code None
[2024-06-26T06:57:20.459+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=997, status='terminated', started='06:56:54') (997) terminated with exit code None
[2024-06-26T06:57:20.460+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=981, status='terminated', started='06:56:54') (981) terminated with exit code None
[2024-06-26T06:57:20.461+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1052, status='terminated', started='06:56:54') (1052) terminated with exit code None
[2024-06-26T06:57:20.596+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=999, status='terminated', started='06:56:54') (999) terminated with exit code None
[2024-06-26T06:57:20.636+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T06:57:20.652+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_minio.py", line 40, in run_selenium_job
    result = functions_instance.get_all_data(driver, page_id, access_token)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fun/fun_page.py", line 246, in get_all_data
    posts_dict = self.get_posts(driver, user_id, access_token)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fun/fun_page.py", line 94, in get_posts
    driver.get(next_url)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 302, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 322, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/poolmanager.py", line 444, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 708, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-26T06:57:20.704+0000] {taskinstance.py:562} DEBUG - Task Duration set to 26.100786
[2024-06-26T06:57:20.709+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2024-06-26T06:57:20.709+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_minio, task_id=run_selenium_task, run_id=manual__2024-06-26T06:56:49.633393+00:00, execution_date=20240626T065649, start_date=20240626T065654, end_date=20240626T065720
[2024-06-26T06:57:20.771+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=944, status='terminated', exitcode=2, started='06:56:53') (944) terminated with exit code 2
[2024-06-26T06:57:20.773+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=996, status='terminated', started='06:56:54') (996) terminated with exit code None
[2024-06-26T06:57:20.775+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=975, status='terminated', started='06:56:54') (975) terminated with exit code None
