[2024-06-27T03:24:18.905+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: test_ue.get_urls_task manual__2024-06-27T03:24:17.400393+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
