[2024-06-25T08:13:03.613+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-25T08:13:03.674+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-25T08:13:03.688+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T08:13:03.721+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: selenium_minio.run_selenium_task manual__2024-06-25T08:13:01.710664+00:00 [queued]>
[2024-06-25T08:13:03.734+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: selenium_minio.run_selenium_task manual__2024-06-25T08:13:01.710664+00:00 [queued]>
[2024-06-25T08:13:03.735+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-25T08:13:03.758+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_selenium_task> on 2024-06-25 08:13:01.710664+00:00
[2024-06-25T08:13:03.765+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=394) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T08:13:03.767+0000] {standard_task_runner.py:63} INFO - Started process 395 to run task
[2024-06-25T08:13:03.766+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'selenium_minio', 'run_selenium_task', 'manual__2024-06-25T08:13:01.710664+00:00', '--job-id', '458', '--raw', '--subdir', 'DAGS_FOLDER/crawl_minio.py', '--cfg-path', '/tmp/tmp4mu3o0k2']
[2024-06-25T08:13:03.768+0000] {standard_task_runner.py:91} INFO - Job 458: Subtask run_selenium_task
[2024-06-25T08:13:03.824+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-25T08:13:03.833+0000] {task_command.py:426} INFO - Running <TaskInstance: selenium_minio.run_selenium_task manual__2024-06-25T08:13:01.710664+00:00 [running]> on host ae041f19a8bf
[2024-06-25T08:13:03.833+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 395)
[2024-06-25T08:13:03.834+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 395)
[2024-06-25T08:13:03.835+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-06-25T08:13:03.890+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-25T08:13:03.957+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='selenium_minio' AIRFLOW_CTX_TASK_ID='run_selenium_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T08:13:01.710664+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T08:13:01.710664+00:00'
[2024-06-25T08:13:03.959+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T08:13:05.493+0000] {logging_mixin.py:188} INFO - ok
[2024-06-25T08:13:29.549+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:13:33.297+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:13:36.785+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:13:53.431+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:13:56.910+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:14:05.732+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:14:10.896+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:14:25.296+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:14:37.439+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:14:41.316+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:14:45.145+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:14:48.733+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:14:52.489+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:14:55.811+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:14:59.333+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:09.708+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:21.291+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:25.384+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:28.481+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:31.305+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:35.954+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:39.443+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:43.344+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:47.153+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:50.314+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:53.501+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:15:57.708+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:16:01.667+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:16:05.354+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:16:08.991+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:16:13.323+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:16:23.993+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:16:31.384+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:16:36.032+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:16:55.082+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:17:17.150+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:17:39.487+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:17:43.717+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:17:48.545+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:17:57.517+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:18:11.306+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:18:15.252+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:18:21.914+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:18:26.419+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:18:39.533+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:18:42.831+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:18:46.980+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:18:49.500+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:18:54.399+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:18:57.397+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:00.435+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:04.358+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:23.130+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:30.989+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:35.367+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:38.573+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:41.584+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:47.526+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:51.113+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:54.449+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:19:59.497+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:02.685+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:05.525+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:08.416+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:11.767+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:16.974+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:19.357+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:22.186+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:24.331+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:26.414+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:28.329+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:35.882+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:44.365+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:49.838+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:52.428+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:20:59.883+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:21:03.682+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:21:07.966+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:21:10.817+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:21:13.409+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:21:15.951+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:21:20.382+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:21:22.676+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:03.082+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:07.231+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:09.255+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:12.331+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:14.897+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:16.776+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:19.041+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:21.394+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:23.850+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:26.412+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:35.664+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:37.617+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:45.089+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:52.295+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:54.351+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:22:59.446+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:23:02.991+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:23:05.141+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:23:07.805+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:23:11.248+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:23:13.422+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:23:15.872+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:23:18.038+0000] {fun_page.py:109} INFO - getting another set
[2024-06-25T08:24:15.111+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 192, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 89, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 435, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 98, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 316, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-06-25T08:24:35.700+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-06-25T08:25:19.557+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-06-25T08:27:30.300+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-06-25T08:27:32.921+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T08:27:32.936+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_minio.py", line 29, in run_selenium_job
    result = functions_instance.get_all_data(driver,page_id, access_token)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fun/fun_page.py", line 246, in get_all_data
    posts_dict = self.get_posts(driver, user_id, access_token)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fun/fun_page.py", line 94, in get_posts
    driver.get(next_url)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome-headless-shell=126.0.6478.114)
Stacktrace:
#0 0x5637e4a978ae <unknown>
#1 0x5637e4768c57 <unknown>
#2 0x5637e47620d6 <unknown>
#3 0x5637e4754bbc <unknown>
#4 0x5637e475627b <unknown>
#5 0x5637e475503b <unknown>
#6 0x5637e475484b <unknown>
#7 0x5637e47546e0 <unknown>
#8 0x5637e4752ba0 <unknown>
#9 0x5637e4752ef4 <unknown>
#10 0x5637e476bf06 <unknown>
#11 0x5637e47efde2 <unknown>
#12 0x5637e47d2b12 <unknown>
#13 0x5637e47ef920 <unknown>
#14 0x5637e47d2893 <unknown>
#15 0x5637e47a32ed <unknown>
#16 0x5637e47a4092 <unknown>
#17 0x5637e4a67256 <unknown>
#18 0x5637e4a6a5f9 <unknown>
#19 0x5637e4a6a0bf <unknown>
#20 0x5637e4a6aa75 <unknown>
#21 0x5637e4a5779f <unknown>
#22 0x5637e4a6adc0 <unknown>
#23 0x5637e4a406c6 <unknown>
#24 0x5637e4a87fb5 <unknown>
#25 0x5637e4a881a2 <unknown>
#26 0x5637e4a96d9a <unknown>
#27 0x7fdb6777b134 <unknown>

[2024-06-25T08:27:33.585+0000] {taskinstance.py:562} DEBUG - Task Duration set to 869.862526
[2024-06-25T08:27:33.637+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2024-06-25T08:27:33.641+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=selenium_minio, task_id=run_selenium_task, run_id=manual__2024-06-25T08:13:01.710664+00:00, execution_date=20240625T081301, start_date=20240625T081303, end_date=20240625T082733
[2024-06-25T08:27:33.844+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 458 for task run_selenium_task (Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome-headless-shell=126.0.6478.114)
Stacktrace:
#0 0x5637e4a978ae <unknown>
#1 0x5637e4768c57 <unknown>
#2 0x5637e47620d6 <unknown>
#3 0x5637e4754bbc <unknown>
#4 0x5637e475627b <unknown>
#5 0x5637e475503b <unknown>
#6 0x5637e475484b <unknown>
#7 0x5637e47546e0 <unknown>
#8 0x5637e4752ba0 <unknown>
#9 0x5637e4752ef4 <unknown>
#10 0x5637e476bf06 <unknown>
#11 0x5637e47efde2 <unknown>
#12 0x5637e47d2b12 <unknown>
#13 0x5637e47ef920 <unknown>
#14 0x5637e47d2893 <unknown>
#15 0x5637e47a32ed <unknown>
#16 0x5637e47a4092 <unknown>
#17 0x5637e4a67256 <unknown>
#18 0x5637e4a6a5f9 <unknown>
#19 0x5637e4a6a0bf <unknown>
#20 0x5637e4a6aa75 <unknown>
#21 0x5637e4a5779f <unknown>
#22 0x5637e4a6adc0 <unknown>
#23 0x5637e4a406c6 <unknown>
#24 0x5637e4a87fb5 <unknown>
#25 0x5637e4a881a2 <unknown>
#26 0x5637e4a96d9a <unknown>
#27 0x7fdb6777b134 <unknown>
; 395)
[2024-06-25T08:27:33.931+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T08:27:34.258+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T08:27:34.282+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
